# Generated by Django 5.0 on 2024-01-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
    ]
