# Generated by Django 5.0 on 2024-01-20 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassignment_date', models.DateTimeField(auto_now_add=True)),
                ('current_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_doctor_reassignments', to=settings.AUTH_USER_MODEL)),
                ('new_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_doctor_reassignments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
