# Generated by Django 5.0 on 2024-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_patientreassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreassignment',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
