# Generated by Django 5.0 on 2024-01-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_patientreassignment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreassignment',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.consultation'),
        ),
    ]
