# Generated by Django 5.0 on 2024-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_patientreassignment_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreassignment',
            name='consultation',
        ),
        migrations.AddField(
            model_name='patientreassignment',
            name='consumption_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientreassignment',
            name='illness',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientreassignment',
            name='medicine_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
