# Generated by Django 5.0 on 2024-01-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_remove_patientreassignment_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreassignment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.department'),
        ),
    ]
